package org.nextframework.report.definition;

public enum ReportSectionType {

	TITLE,
	PAGE_HEADER,
	PAGE_FOOTER,
	COLUMN_HEADER,
	COLUMN_FOOTER,
	GROUP,
	GROUP_HEADER,
	GROUP_FOOTER,
	GROUP_DETAIL,
	DETAIL_HEADER,
	DETAIL,
	SUMARY_DATA_HEADER,
	SUMARY_DATA_DETAIL,
	FIRST_PAGE_HEADER,
	LAST_PAGE_FOOTER,
	SUMARY

}